# Generated by Django 3.0.5 on 2020-04-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USERS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('access_key', models.CharField(max_length=128)),
                ('token', models.CharField(max_length=128)),
                ('info', models.CharField(max_length=2048)),
            ],
            options={
                'verbose_name': '用户数据表',
                'db_table': 'dkt_users',
            },
        ),
    ]
