# Generated by Django 3.0.5 on 2020-04-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='COURSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(default='', max_length=64)),
                ('s_account', models.CharField(default='', max_length=64)),
                ('t_account', models.CharField(default='', max_length=64)),
                ('start_time', models.IntegerField(default=0)),
                ('finish_time', models.IntegerField(default=0)),
                ('info', models.CharField(default='', max_length=2048)),
            ],
            options={
                'verbose_name': '课程表',
                'db_table': 'dkt_course',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='_t',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='access_key',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='users',
            name='account',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='users',
            name='info',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='users',
            name='token',
            field=models.CharField(default='', max_length=128),
        ),
    ]
