# Generated by Django 3.0.1 on 2020-05-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20200509_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='MESSAGES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(default='', max_length=64)),
                ('sender', models.CharField(default='', max_length=64)),
                ('receiver', models.CharField(default='', max_length=64)),
                ('_t', models.IntegerField(default=1589105519)),
                ('msg', models.CharField(default='', max_length=2048)),
            ],
            options={
                'verbose_name': '消息表',
                'db_table': 'dkt_messages',
                'ordering': ('-_t',),
            },
        ),
        migrations.DeleteModel(
            name='MESSAGE',
        ),
    ]
