# Generated by Django 3.0.6 on 2020-05-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20200523_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending',
            name='_t',
            field=models.IntegerField(default=1590246373),
        ),
    ]
