# Generated by Django 3.0.6 on 2020-05-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20200523_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='passed_periods',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='total_periods',
            field=models.IntegerField(default=0),
        ),
    ]
