# Generated by Django 3.0.6 on 2020-05-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20200526_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='checklist',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='users',
            name='trolley',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
